jobs:
  check:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./verify/main

name: Action

on:
  schedule:
    - cron: "20 1/3 * * *"
